name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Build image
        run: |
          docker-compose -f docker-compose.test.yml build

      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml run --rm tests
